### PR TITLE
Update Sodaq_UBlox_GPS.cpp

### PR DESCRIPTION
**Pull request by pablomargareto**
Small error parsing the E/W property of the GPRMC messages. It is not detecting properly the sign of the longitude for those on the west

### CODE REVIEW

**Comment by jwillemsen** [comment]
Proposed patch looks correct to me, field 6 is E/W, see https://www.u-blox.com/sites/default/files/products/documents/u-blox7-V14_ReceiverDescrProtSpec_%28GPS.G7-SW-12001%29_Public.pdf

**Comment by pablomargareto** [comment]
Yes, but you already parse that field a couple of lines above. This is the typical "copy/paste" mistake! :)

You are parsing the W/E field of the latitude and assigning it to the longitude.

I realized quickly because if the GPS is West from Greenwich, the longitude that the GPS returns has the wrong sign.

**Comment by jwillemsen** [comment]
@pablomargareto I was just supporting your PR, hopefully your and mine PR gets merged soon

**Comment by jwillemsen** [comment]
Any reason you closed this one? Shouldn't sodaq fix this in their repo?

**Comment by pablomargareto** [comment]
Oh, I am sorry, I didn't know how this works... shall Sodaq close it?

**Comment by jwillemsen** [comment]
Sodaq has to merge it, that will close it and include your changes into master

**Comment by pablomargareto** [comment]
Got it! 👍

**Comment by keestux** [comment]
The change is indeed correct. I'll apply it (cherry-pick probably).

The format of the commit message isn't quite as I like it, but I'll take is anyway.
The first line of the commit message must be a brief and clear description what has changed. And your
`Update Sodaq_UBlox_GPS.cpp` is not a good one :-) The rest of the commit message is OK. Maybe the first sentence should have been used as the first line of the commit message

**Comment by keestux** [comment]
In general you can leave a Pull Request until it is applied or rejected. And picking a good branch name for a pull request is sometimes a challenge.

**Comment by pablomargareto** [comment]
Ok! I see... I will try to be more concise with the descriptions next time! :)

**Comment by SodaqMoja** [comment]
It's merged. I'll close the PR

**Pull request closed without merging**
